---
title: Shohei Shibata
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
email: shohei.shibata.dev@gmail.com
description: Personal website for Shohei Shibata, a freelance web developer. A blog
  describing his learning experiences in coding.
twitter_username: _shoheishibata_
github_username: shohei-shibata
plugins:
- jekyll-feed
- jekyll-archives
google_analytics: true
jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
    category: "/blog/categories/:name/"
