title: Shohei Shibata
timezone: UTC
email: shohei.shibata.dev@gmail.com
description: Personal website for Shohei Shibata, a web developer.
twitter_username: _shoheishibata_
github_username: shohei-shibata
collections:
  projects:
    output: true
plugins:
- jekyll-feed
