---
title: Shohei Shibata
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: shohei51@gmail.com
description: Blog
baseurl: ''
url: https://shohei-shibata.github.io
twitter_username: ''
github_username: shohei-shibata
header_pages: 
markdown: kramdown
theme: minima
plugins: 
excerpt_separator: "<!--more-->"
